### ISSUE TITLE
Error Encountered When Creating Wallet Instance from JSON File due to Hash Issue

### ISSUE THREAD

**Issue by IDKNWHORU** [CityOfZion/neo-mamba#278]
During the execution of the `__init__.py` in the example, the following error occurs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goldriver/Workspace/ludium/neo-mamba/examples/nep-11-airdrop.py", line 8, in <module>
    from examples import shared
  File "/home/goldriver/Workspace/ludium/neo-mamba/examples/shared/__init__.py", line 15, in <module>
    user_wallet = Wallet.from_file(f"{shared_dir}/user-wallet.json", passwords=["123"])
  File "/home/goldriver/Workspace/ludium/neo-mamba/neo3/wallet/wallet.py", line 354, in from_file
    return cls.from_json(json.load(f), passwords)
  File "/home/goldriver/Workspace/ludium/neo-mamba/neo3/wallet/wallet.py", line 324, in from_json
    account_from_json = account.Account.from_json(
  File "/home/goldriver/Workspace/ludium/neo-mamba/neo3/wallet/account.py", line 568, in from_json
    private_key = cls.private_key_from_nep2(
  File "/home/goldriver/Workspace/ludium/neo-mamba/neo3/wallet/account.py", line 646, in private_key_from_nep2
    script_hash = coreutils.to_script_hash(
  File "/home/goldriver/Workspace/ludium/neo-mamba/neo3/core/utils.py", line 72, in to_script_hash
    data_ = hashlib.new("ripemd160", intermediate_data).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```
My Environment Settings:
```
Python version: 3.10.12
OS: Ubuntu 22.04.3 LTS
```

**Comment by IDKNWHORU** [comment]
I tried the method mentioned in the [document](https://stackoverflow.com/questions/72409563/unsupported-hash-type-ripemd160-with-hashlib-in-python), and after that, no more errors occurred.

**Comment by ixje** [comment]
yeah this is an unfortunate openssl issue, more on their blog <https://www.openssl.org/blog/blog/2022/10/18/rmd160-and-the-legacy-provider/>
